In [1]:
import numpy as np

In [2]:
print(range(10))
print(*range(10))
print(*range(0, 10))
print(*range(0, 10, 1))

for i in range(10) :
  print(i)

print(*range(1,11))

range(0, 10)
0 1 2 3 4 5 6 7 8 9
0 1 2 3 4 5 6 7 8 9
0 1 2 3 4 5 6 7 8 9
0
1
2
3
4
5
6
7
8
9
1 2 3 4 5 6 7 8 9 10


In [3]:
n = int(input())
print(n)

ValueError: invalid literal for int() with base 10: '1 2 4 3 6'

In [ ]:
result = 0
for i in range(1, n + 1):
    result += i
    print(result)

print(result)

1
3
6
10
15
21
28
36
45
55
55


In [ ]:
cnt = 1
result = 0
while cnt <= n:
    result += cnt
    cnt += 1
    print(result)

print(result)

1
3
6
10
15
21
28
36
45
55
55


In [ ]:
sum(range(1, n + 1))

55

In [ ]:
print(*range(1, n + 1, 1))
print(*range(n, 0, -1))

1 2 3 4 5 6 7 8 9 10
10 9 8 7 6 5 4 3 2 1


In [ ]:
print(np.array(range(1, n + 1, 1)))
print(np.array(range(n, 0, -1)))
print(np.array(range(1, n + 1, 1))+np.array(range(n, 0, -1)))

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]
[11 11 11 11 11 11 11 11 11 11]


In [ ]:
result = (1 + n) * n / 2
print(result)

55.0


In [ ]:
print(*range(10,0))

In [12]:
in_value = list(map(int, input().split())) 
print(in_value)
print(type(in_value))

[7, 1, 4, 3, 6]
<class 'list'>


In [ ]:
# - 값일 경우
in_value = map(int, input().split())
print(in_value)
print(type(in_value))

max_value = 0
for a in in_value:
    if max_value < a:
        max_value = a
print(max_value) 

<class 'map'>
0


In [20]:
print(min(in_value))
print(max(in_value))

ValueError: min() iterable argument is empty

In [17]:
in_value = list(map(int, input().split()))

max_value = in_value[0]
for a in in_value[1:]:
    if max_value < a:
        max_value = a

print(max_value)

9
